### ISSUE TITLE
activating x86 container on x64 host causes  

### ISSUE THREAD

**Issue by piexil** [FooBarWidget/holy-build-box#51]
`+ /hbb_exe/activate-exec
/hbb/activate_func.sh: line 38: /opt/rh/devtoolset-8/enable: No such file or directory`

reason is due to 
`function activate_holy_build_box_deps_installation_environment() {
        if [ "$(uname -m)" != x86_64 ]; then
                DEVTOOLSET_VER=7
        else
                DEVTOOLSET_VER=8
        fi`
in /hbb/activate_func.sh 
devtoolset 8 isn't readily available or in the container for x86, should always be set to 7 for the x86 container.

**Comment by FooBarWidget** [comment]
When using x86 container on x64, you should run all commands with `linux32` in order for the container to believe that it's actually on an x86 system. Otherwise, tools like `uname` will report that it's on x64. See this document: https://github.com/FooBarWidget/holy-build-box/blob/v2/BUILDING-32-BIT-BINARIES.md

**Comment by piexil** [comment]
ah of course, I'm sorry I missed this. Thank you!
